In [3]:
import numpy as np

## DataTypes & Attributes

In [5]:
# NumPy's main datatype is ndarray
al = np.array([1,2,3])

In [3]:
al

array([1, 2, 3])

In [6]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a3 = np.array([[[1,2,3],[4,5,6], [7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [6]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a3 = np.array([[[2,17], [45, 78]], [[88, 92], [60, 76]],[[76,33],[20,18]]])

In [9]:
a3

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [10]:
a3.shape

(3, 2, 2)

In [11]:
#Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## 2. Creating arrays

In [12]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [13]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [19]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[8, 4, 7, 4, 2],
       [0, 4, 1, 3, 8],
       [6, 1, 1, 5, 7]])

In [20]:
random_array_2 = np.random.random((3,5))
random_array_2

array([[0.7435575 , 0.63951524, 0.22151855, 0.0838745 , 0.65369284],
       [0.70683029, 0.82185222, 0.12591697, 0.39189301, 0.62596771],
       [0.48778873, 0.13545794, 0.04134729, 0.84112242, 0.43034998]])

In [22]:
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## 3. Viewing array and matrices

In [23]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
al

array([1, 2, 3])

In [11]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [12]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
al[0]

1

In [14]:
a2[0]

array([1, 2, 3])

In [15]:
a2.shape

(2, 3)

In [16]:
a2[1]

array([4, 5, 6])

In [17]:
a3.shape

(2, 3, 3)

In [18]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [21]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[1, 8, 9, 2, 7],
         [4, 4, 2, 1, 5],
         [2, 8, 7, 5, 9],
         [0, 7, 6, 2, 7]],

        [[5, 8, 2, 3, 0],
         [8, 9, 5, 4, 4],
         [9, 4, 7, 1, 7],
         [5, 5, 1, 1, 7]],

        [[0, 9, 5, 3, 7],
         [5, 5, 3, 0, 8],
         [3, 0, 1, 0, 1],
         [2, 3, 7, 1, 8]]],


       [[[2, 3, 0, 5, 8],
         [3, 2, 3, 0, 1],
         [5, 6, 5, 1, 5],
         [5, 3, 7, 9, 6]],

        [[4, 3, 6, 5, 0],
         [6, 5, 7, 7, 2],
         [8, 8, 5, 6, 4],
         [4, 6, 9, 0, 6]],

        [[1, 6, 9, 7, 0],
         [5, 0, 4, 7, 5],
         [9, 7, 6, 3, 9],
         [4, 1, 6, 7, 2]]]])

In [23]:
# get the first 4 numbers of the inner most array
a4[:,:,:,:2]

array([[[[1, 8],
         [4, 4],
         [2, 8],
         [0, 7]],

        [[5, 8],
         [8, 9],
         [9, 4],
         [5, 5]],

        [[0, 9],
         [5, 5],
         [3, 0],
         [2, 3]]],


       [[[2, 3],
         [3, 2],
         [5, 6],
         [5, 3]],

        [[4, 3],
         [6, 5],
         [8, 8],
         [4, 6]],

        [[1, 6],
         [5, 0],
         [9, 7],
         [4, 1]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [24]:
al

array([1, 2, 3])

In [26]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [27]:
al + ones

array([2., 3., 4.])

In [28]:
al - ones

array([0., 1., 2.])

In [29]:
al * ones

array([1., 2., 3.])

In [30]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
al * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [33]:
al / ones

array([1., 2., 3.])

In [34]:
a2 / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [35]:
a2 // 2

array([[0, 1, 1],
       [2, 2, 3]], dtype=int32)

In [36]:
al % 2

array([1, 0, 1], dtype=int32)

In [37]:
np.exp(al)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [38]:
np.log(al)

array([0.        , 0.69314718, 1.09861229])